# Analyze Next Steps Hook
# 手動トリガーで次の課題を分析するhook
#
# 用途: 検証完了後、または任意のタイミングで次のステップを分析したいとき

name: "Analyze Next Steps"
description: "現在の課題を分析し、次の実装を提案する（手動トリガー）"

trigger:
  type: "manual"

action:
  type: "sendMessage"
  message: |
    ## 次のステップ分析

    現在のプロジェクト状態を分析し、次に取り組むべき課題を特定します。

    ### 参照ファイル
    - #[[file:.kiro/reports/CONCLUSIONS.md]]
    - #[[file:.kiro/steering/project-rules.md]]
    - #[[file:.kiro/ideas/README.md]]

    ### 分析フレームワーク

    #### 1. 現状の課題リスト
    CONCLUSIONS.mdから以下を抽出：
    - 未解決の問い（Q1-Q3）
    - 検証中の仮説（H1-H12）
    - 最近の発見と残りの懸念点

    #### 2. 優先順位の判断基準
    以下の観点で優先順位を決定：
    
    a) **活発レジームの維持・拡張**
       - 現在regenRate=0.016-0.032で「活発」レジームに入れている
       - この状態を維持しつつ、より複雑な創発を観測できるか
    
    b) **非恣意性原則との整合**
       - 新しい実装が「特定の成果を誘導」していないか
       - 公理予算を消費する必要があるか
    
    c) **検証可能性**
       - 実装後、明確な観測指標で検証できるか
       - 既存のメトリクス/ログで観測可能か

    #### 3. 技術的負債の確認
    前回指摘された懸念点：
    - maintainerの+1 hop知覚が意思決定に使われていない
    - Beacon強度の定義が行動系と統計でズレている
    - 情報→行動の接続（artifact.dataを読んでrepair効率に影響）が未実装

    ### 出力
    1. **推奨する次の実装**（1つに絞る）
    2. **その理由**（設計思想との整合性を含む）
    3. **実装アプローチ**（概要レベル）
    4. **検証方法**（どのメトリクスで成功を判断するか）

    分析を開始してください。
