# Next Iteration Hook
# 検証完了後に次の課題を洗い出し、実装を提案するhook
#
# トリガー: CONCLUSIONS.mdが更新されたとき（検証完了の指標）
# 動作: 
#   1. 現在の課題（未解決の問い、検証中の仮説）を洗い出す
#   2. プロジェクト目的（設計思想の憲法）と照合
#   3. 次に取り組むべき実装を提案・実行

name: "Next Iteration"
description: "検証完了後に次の課題を洗い出し、実装を提案する"

trigger:
  type: "onFileSave"
  pattern: ".kiro/reports/CONCLUSIONS.md"

action:
  type: "sendMessage"
  message: |
    ## 検証サイクル完了検知

    CONCLUSIONS.mdが更新されました。イテレーションワークフローに従って次のステップを特定します。

    ### 参照ファイル
    - #[[file:.kiro/steering/iteration-workflow.md]]
    - #[[file:.kiro/reports/CONCLUSIONS.md]]
    - #[[file:.kiro/steering/project-rules.md]]

    ### Phase 2: 次のステップの特定

    以下の優先順位で分析してください：

    1. **技術的負債の確認**
       - iteration-workflow.mdの「技術的負債」セクションを確認
       - 優先度「高」の項目があれば、それを最優先

    2. **検証中の仮説の確認**
       - CONCLUSIONS.mdの「仮説（検証中）」セクションを確認
       - 検証可能な仮説を選択

    3. **未解決の問いへのアプローチ**
       - Q1-Q3の検証に必要な前提条件を確認

    ### Phase 3: 非恣意性チェック

    次のステップを決定する前に確認：
    - 新しい公理を追加する必要があるか？
    - 特定の成果を誘導していないか？
    - 観測のみの原則に沿っているか？

    ### 出力

    1. **推奨する次の実装**（1つに絞る）
    2. **その理由**（設計思想との整合性を含む）
    3. **実装アプローチ**（概要レベル）
    4. **公理予算への影響**（新規公理が必要か）

    分析を開始し、スペック作成に進んでください。
