# Next Iteration Hook
# 検証完了後に次の課題を洗い出し、実装を提案するhook
#
# トリガー: CONCLUSIONS.mdが更新されたとき（検証完了の指標）
# 動作: 
#   1. 現在の課題（未解決の問い、検証中の仮説）を洗い出す
#   2. プロジェクト目的（設計思想の憲法）と照合
#   3. 次に取り組むべき実装を提案・実行

name: "Next Iteration"
description: "検証完了後に次の課題を洗い出し、実装を提案する"

trigger:
  type: "onFileSave"
  pattern: ".kiro/reports/CONCLUSIONS.md"

action:
  type: "sendMessage"
  message: |
    ## 検証サイクル完了検知

    CONCLUSIONS.mdが更新されました。次のイテレーションを開始します。

    ### 分析対象
    1. **未解決の問い** (#[[file:.kiro/reports/CONCLUSIONS.md]] の「未解決の問い」セクション)
    2. **検証中の仮説** (同ファイルの「仮説（検証中）」セクション)
    3. **残りの懸念点** (前回の会話で指摘された技術的課題)

    ### 照合対象
    - **設計思想の憲法** (#[[file:.kiro/steering/project-rules.md]] の「設計思想の憲法」)
    - **プロジェクトビジョン** (#[[file:.kiro/ideas/README.md]])

    ### タスク
    以下を実行してください：

    1. **課題の優先順位付け**
       - 「活発レジーム」を維持・拡張するために最も重要な課題は何か
       - 非恣意性原則に違反せずに実装可能な改善は何か
       - 公理予算を消費せずに検証可能な仮説は何か

    2. **次の実装提案**
       - 上記の分析に基づき、次に取り組むべき実装を1つ選定
       - その実装が「観測のみ」原則に沿っているか確認
       - 必要であれば新しいスペックを作成

    3. **実装の実行**
       - 提案が承認されたら、実装に着手
       - 実装完了後、検証シミュレーションを実行
       - 結果をレポートにまとめ、CONCLUSIONS.mdを更新

    **注意**: 恣意的な誘導を避け、観測結果に基づいて判断すること。
