# Post-Simulation Report Hook
# シミュレーション実行後にレポート作成を促すhook
#
# トリガー: runs/ディレクトリに新しいJSONファイルが保存されたとき

name: "Post-Simulation Report"
description: "シミュレーション実行後にレポート作成を促す"

trigger:
  type: "onFileSave"
  pattern: "runs/*.json"

action:
  type: "sendMessage"
  message: |
    ## シミュレーション完了検知

    新しいシミュレーション結果が保存されました。

    ### タスク
    1. **結果の分析**
       - 保存されたJSONファイルを読み込み、主要メトリクスを確認
       - 既存の結論・仮説と照合

    2. **レポート作成の判断**
       - 新しい発見があれば、個別レポート（YYYY-MM-DD-{topic}.md）を作成
       - 既存の仮説を支持/棄却する証拠があれば記録

    3. **CONCLUSIONS.md更新の判断**
       - 結論を追加/更新する必要があるか
       - 仮説のステータスを変更する必要があるか

    **注意**: 
    - レポートは「観測結果」であり、シミュレーションを誘導するために使わない
    - 恣意的な解釈を避け、データに基づいて記述する
